<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Доступ Запрещен</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"/>
</head>
<body>
<div class="col-3 alert alert-warning">
    <p>У вас нет доступа для просмотра этой страницы</p>
    <a href="/passwords"><p class="ml-4">Нажмите сюда, чтобы вернуться</p></a>
</div>
</body>
</html>