<#import "/spring.ftl" as spring/>
<html lang="ru">
<head>
    <link rel="stylesheet" type="text/css" href="../log_in.css">
    <title>Менеджер паролей</title>
</head>
<body>
<h1 style="margin-left: 40%">Менеджер паролей</h1>
<div class="wrapper">
    <a href="/login">
        <button class="main_menu_buttons">Войти</button>
    </a> <br>
    <a href="/signUp">
        <button class="main_menu_buttons">Зарегистрироваться</button>
    </a>
</div>
</body>
<html>